export const FontSizes = {
  FONT_SIZE_META: 13,
  FONT_SIZE_META_2: 14,
  FONT_SIZE_BASE: 15,
  FONT_SIZE_BASE_2: 16,
  FONT_SIZE_BASE_3: 18,
  FONT_SIZE_HEADER_3: 19,
  FONT_SIZE_HEADER_4: 24,
  FONT_SIZE_HEADER_2: 32,
};
